import Link from "next/link"
import styles from '../styles/Home.module.css'
import Head from "next/head"
import 'bootstrap/dist/css/bootstrap.css'
import NavDropdown from 'react-bootstrap/Nav'
import Nav from 'react-bootstrap/Nav'
import { Button, Container, Form, FormControl, Navbar } from "react-bootstrap"
import Image from "next/image"



const flashcardTypes: string[] = ["Mental card","Input card","Multiple choice card", "Salade"];


export const Layout: React.FC = ({children}) => {
  return (

    <div>
       <Head>
        <title>Game catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <header className="p-3 bg-dark text-white">
      <div className="container">
        <div className="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <Link
            href="/"
          >
            <a className="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            HOME   {"   "}
          </a>
        </Link>
          <ul className="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">

          </ul>

         {/* <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
            <NavDropdown title="Pick your game" id="basic-nav-dropdown" onSelect={setFlashcard}>
              {flashcardTypes.map((flashcard, index) => {
                  return (
                <NavDropdown.Item  key={index} value={flashcard} eventKey={flashcard}>
                  {flashcard}
                </NavDropdown.Item >
              )})}
            </NavDropdown>
          </Nav>
        </Navbar.Collapse> */}



           <div className="text-end" style={{display: 'flex',  justifyContent:'center', alignItems:'center'}}>
           <a href="/cart">
             <Image src="/panier.png"  alt="cart_logo" width= "50px" height="50px"/>
             </a>
             <a href="/profile">
             <Image src="/Profile-Pic-Icon.png"  alt="profile_logo" width= "50px" height="50px"/>
             </a>
            <Button href="/api/auth/login" type="button" className="btn btn-outline-light me-2">
              Login
            </Button>
            <Button type="button" className="btn btn-outline-light me-2" href="/api/auth/logout">
              Logout
            </Button>
          </div>
         </div>
      </div>
    </header>
      </nav>



      <article>
        {children}
      </article>

      <footer className={styles.footer}>
        <p>
          Powered by Baptiste Verkindere with Next.js
        </p>
      </footer>


    </div>
  )
}

export default flashcardTypes;
