import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetServerSideProps } from 'next'
import Card from 'react-bootstrap/Card'
import Button from 'react-bootstrap/Button'
import 'bootstrap/dist/css/bootstrap.css'
import { Layout } from '../components/layout'
import Row from 'react-bootstrap/Row'

type platforms = {
  id : string,
  name: string,
}

type cover = {
  url: string,
  width: number,
  height: number,
}

type game = {
  id: string,
  name: string,
  slug: string,
  category: string,
  platforms: platforms[],
  cover: cover,
}

type myReactComponent = {
  games: game[],
}

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch("http://videogame-api.fly.dev/games")
  const gamesResponse = await response.json();
  const games: game[] = gamesResponse.games
  console.log(games)
  return {
    props: {
      games: games,
    },
  }
}

const Home: NextPage<myReactComponent> = ({games}) => {
  console.log("test===",games)
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Game catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the ultimate Video-game platform
        </h1>

        <p className={styles.description}>
          Select your favorite game
        </p>

      <div>
        {console.log("test2", games)}
        <Row xs={1} md={2} className="g-4">
      {games.map((games, index) => {
        return (
          <Card style={{ width: '18rem' }} key={index} bg="light">
            <Card.Img variant="top" src={games.cover?.url} width="250px" height="350px"/>
            <Card.Body>
              <Card.Title>{games.name}</Card.Title>

            </Card.Body>
            <Card.Footer background-color="#fff" >
              <Button variant="primary">Learn more</Button>
              </Card.Footer>
          </Card>
        )
      })}
      </Row>

      </div>

      </main>
      </div>
    </Layout>
  )
}

export default Home
